name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-test:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
    - name: Build gem
      run: bundle exec gem build salsa20.gemspec
    - name: Install gem
      run: bundle exec gem install --verbose ./salsa20-*.gem
      continue-on-error: true
    - name: Print gem make log
      run: cat D:/a/salsa20-ruby/salsa20-ruby/vendor/bundle/ruby/3.0.0/extensions/x64-mingw32/3.0.0/salsa20-0.1.3/gem_make.out
      continue-on-error: true
